Fix error in extractTypeMapFromTypeDefs
Error: `TypeError: Cannot read property 'value' of undefined`
when `t` is `{ kind: 'SchemaDefinition', ... }` (which has no `name`).